#! /bin/sh

# Clones a remote yaul repository (with all submodules) and creates a source
# tarball from it.
#
# Usage:
#   build-tarball.sh              # creates tarball for master/head
#   build-tarball.sh yaul-0.1.2a  # creates tarball from a (named) tag/commit
#
# The tarball is created in the current working dir.

set -e

SCRIPTDIR=`dirname $0`
TOPSRCDIR=`readlink -f ${SCRIPTDIR}/..`
OUTDIR=`readlink -f ${TOPSRCDIR}/..`

# Make temporary directory
TMPDIR=`mktemp -d`

if [ $# -ge 1 ]; then
  REF=$1
else
  echo "error: missing argument 'ref'" >&2;
  echo "usage:   `basename $0` <ref>" >&2;
  echo "example: `basename $0` v0.1.0" >&2;
  echo "example: `basename $0` HEAD" >&2;
  echo "example: `basename $0` 'HEAD~1'" >&2;
  exit 1;
fi

# Clone the remote repository and checkout the REF
REMOTE='git@github.com:ptomulik/yaul'
(cd ${TMPDIR} && git clone --recursive ${REMOTE} yaul)

if (cd ${TMPDIR}/yaul && (git tag | grep -w $REF)) ; then
  VREG1='s/^\(v\|yaul-\)\([0-9]\+\.[0-9]\+\.[0-9]\+[-a-z0-9]*\)$/\2/';
  VERSION=`echo ${REF} | sed -e ${VREG1}`
else
  VERSION=`(cd ${TMPDIR}/yaul && git rev-parse --short ${REF})`
fi

(cd ${TMPDIR}/yaul && git checkout -b "yaul-tgz" ${REF} && git submodule update)

# Extract sources from top-level git repo
( cd "${TMPDIR}/yaul" && \
  git archive --format=tar --prefix="yaul-${VERSION}/" \
              --output=${TMPDIR}/yaul.tar HEAD );
( cd ${TMPDIR} && tar -xf yaul.tar && rm yaul.tar )

# Extract sources from all submodules
MODS=`(cd ${TMPDIR}/yaul && git submodule status | awk '{print $2}')`
for MOD in ${MODS}; do
  ( cd "${TMPDIR}/yaul/${MOD}" && \
    git archive --format=tar --prefix="yaul-${VERSION}/${MOD}/" \
                --output=${TMPDIR}/submodule.tar HEAD );
  ( cd ${TMPDIR} && tar -xf submodule.tar && rm submodule.tar )
done

# Remove files that shouldn't enter the tarball
( cd ${TMPDIR}/yaul-${VERSION} && find . -name '.git*' -delete );
( cd ${TMPDIR}/yaul-${VERSION} && find . -name '.travis.yml' -delete );
( cd ${TMPDIR}/yaul-${VERSION} && rm -rf bin.v2/ boost/ yaul/ );

# Create the finall tarball
( cd ${TMPDIR} && tar -czf yaul-${VERSION}.tar.gz yaul-${VERSION} );

# Copy tarball to the current working dir
cp ${TMPDIR}/yaul-${VERSION}.tar.gz ${OUTDIR}

echo "created ${OUTDIR}/yaul-${VERSION}.tar.gz"

# Cleanup the temporary directory
rm -rf ${TMPDIR}
